apiVersion: apps/v1
kind: Deployment
metadata:
  name: IMAGE_NAME
  namespace: todo-namespace
spec:
  selector:
    matchLabels:
      app: IMAGE_NAME
  template:
    metadata:
      labels:
        app: IMAGE_NAME
      namespace: todo-namespace
    spec:
      serviceAccountName: todo-sa
      containers:
      - name: IMAGE_NAME
        image: europe-west1-docker.pkg.dev/PROJECT_ID/gke-playground/IMAGE_NAME:GIT_TAG
        ports:
        - containerPort: 8080