apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-deployment-name
  namespace: todo-namespace
spec:
  selector:
    matchLabels:
      app: your-app-label
  template:
    metadata:
      labels:
        app: your-app-label
    spec:
      serviceAccountName: todo-sa
      containers:
      - name: your-container-name
        image: europe-west1-docker.pkg.dev/PROJECT_ID/gke-playground/your-image-name:your-git-tag
        ports:
        - containerPort: 8080
