name: Build,Push and Deploy to GKE
on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  IMAGE_NAME: fe-ms
  GKE_CLUSTER: todo-gke
  REGION: europe-west4
  DEPLOYMENT_NAME: fe-ms

jobs:
  build-push-gcr:
    name: Build and Push to GCPBuild and Push to GCP
    runs-on: ubuntu-latest

    permissions:
      id-token: write 
      contents: read  

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}

      - name: Authenticate to WIF
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/507085571061/locations/global/workloadIdentityPools/gke-pool-tung/providers/gke-playground-provider
          service_account: github-actions@cst-pbag-aiml-test.iam.gserviceaccount.com
          token_format: access_token
          export_environment_variables: true
    
      - name: Automatic Tagging of Releases
        id: increment-git-tag
        run: |
          bash ./scripts/git_update_tag.sh -v patch

      - name: Build and push Docker image
        env:
          GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        run: |-
          gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet
          docker build -t europe-west1-docker.pkg.dev/$PROJECT_ID/gke-playground/$IMAGE_NAME:latest .
          docker build -t europe-west1-docker.pkg.dev/$PROJECT_ID/gke-playground/$IMAGE_NAME:$GIT_TAG .
          docker push europe-west1-docker.pkg.dev/$PROJECT_ID/gke-playground/$IMAGE_NAME:latest
          docker push europe-west1-docker.pkg.dev/$PROJECT_ID/gke-playground/$IMAGE_NAME:$GIT_TAG

      - name: Get GKE credentials
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.REGION }}

      - name: Deploy to GKE
        env:
          GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        run: |-
          sed -i "s/PROJECT_ID/$PROJECT_ID/g" gke-deployment.yml
          sed -i "s/IMAGE_NAME/$IMAGE_NAME/g" gke-deployment.yml
          sed -i "s/MY_LABEL/$MY_LABEL/g" gke-deployment.yml
          sed -i "s/GIT_TAG/$GIT_TAG/g" gke-deployment.yml
          kubectl apply -f gke-deployment.yml